Shotgun bullet implement according to issue #1278
DonBruce64/MinecraftTransportSimulator pull request #1282
Opened 2022-08-07 15:50 UTC by ktokto313

As the title says and a little patch for implement bullet "hardness" for bullet breaking glass only which can be removed later on

2022-08-08 09:15 UTC, ktokto313 commented
Why is the log, still printing welcome to beta 7 lol, can someone fix it for me?

2022-08-09 00:47 UTC, DonBruce64 requested changes

2022-08-09 00:47 UTC, DonBruce64 commented on src/main/java/minecrafttransportsimulator/entities/instances/PartGun.java
> +                                        randomBulletVelocity.rotate(firingSpreadRotation);
This won't work here.  You need to apply the random rotation before you get the actual velocity.  The rotation applied is relative to the orientation of the gun, and gets applied before the matrix rotations that orient the velocity to the gun.  This should be in "setBulletSpawn" with the bullet spread, not here.

2022-08-09 00:47 UTC, DonBruce64 commented on src/main/java/minecrafttransportsimulator/entities/instances/PartGun.java
> +                                    Point3D randomBulletVelocity = bulletVelocity;
Don't do this.  This doesn't copy the variable.  This just takes it and changes its name in the middle of the code.  That's just confusion.  So really, you're editing bulletVelocity in all the calls below.

2022-08-09 00:47 UTC, DonBruce64 commented on src/main/java/minecrafttransportsimulator/entities/instances/PartGun.java
> +                            } else
You do an else here to do the normal spawn, but this means that you still create new bullets on lines 279 though 290, just you ignore those bullets you created and re-create them.  That's bad, as it wastes processing power.

2022-08-09 00:47 UTC, DonBruce64 commented on src/main/java/minecrafttransportsimulator/entities/instances/PartGun.java
> +                                        randomBulletVelocity.rotate(firingSpreadRotation);
FYI, changing the logic for this will make all other comments not matter much.  Other comments are for your information.

2022-08-09 05:09 UTC, ktokto313 commented
@DonBruce64 Here is the fix, i tried to redo it as you say, there is still flaw in it imo, i hope i get further opinion of yours!

2022-08-10 13:15 UTC, DonBruce64 requested changes

2022-08-10 13:15 UTC, DonBruce64 commented on src/main/java/minecrafttransportsimulator/entities/instances/PartGun.java
> -                                newBullet = new EntityBullet(bulletPosition, bulletVelocity, bulletOrientation, this);
This bullet won't go the right way.  It never gets its spawn set.

2022-08-10 13:15 UTC, DonBruce64 commented on src/main/java/minecrafttransportsimulator/entities/instances/PartGun.java
> +                                if (loadedBullet.definition.bullet.turnRate > 0) {
There's really no reason to check turn rate for pellets.  They will never be missiles.

2022-08-10 13:15 UTC, DonBruce64 commented on src/main/java/minecrafttransportsimulator/entities/instances/PartGun.java
> +                bulletVelocity.rotate(firingSpreadRotation);
Due to the property of rotations, this won't work if the gun has a bullet spread factor.  I would say to add both the spread's X and Y components, and then rotate, but you may not want to use the gun's bullet spread with pellets.  Since that'll just double-up on the spread values.  Would be a @LauraDarkez question.

2022-08-10 20:24 UTC, boot2big commented on src/main/java/minecrafttransportsimulator/entities/instances/PartGun.java
> +                bulletVelocity.rotate(firingSpreadRotation);
I would like to comment on that too though, afaik shorter barrels will make the pellets spread out more than longer barrels, so maybe BSF should have an effect alongside PSF

2022-08-11 03:51 UTC, ktokto313 commented on src/main/java/minecrafttransportsimulator/entities/instances/PartGun.java
> +                                if (loadedBullet.definition.bullet.turnRate > 0) {
why not, they can make sci-fi shotgun now :(

2022-08-11 03:52 UTC, ktokto313 commented on src/main/java/minecrafttransportsimulator/entities/instances/PartGun.java
> -                                newBullet = new EntityBullet(bulletPosition, bulletVelocity, bulletOrientation, this);
Yes, thank you for reminding me that, i always work too fast and it turned out to be dumb and inefficient.

2022-08-11 03:54 UTC, ktokto313 commented on src/main/java/minecrafttransportsimulator/entities/instances/PartGun.java
> +                bulletVelocity.rotate(firingSpreadRotation);
Yes, I am not fully understood how vector 3d work, that's totally not my intention

2022-08-11 14:01 UTC, DonBruce64 commented on src/main/java/minecrafttransportsimulator/entities/instances/PartGun.java
> +                bulletVelocity.rotate(firingSpreadRotation);
If the spread should be cumulative, then we can make it so.  But that's only if that is the case.  @Ilya-torshov gets a ping here too about this.

2022-08-13 08:35 UTC, LauraDarkez commented on src/main/java/minecrafttransportsimulator/entities/instances/PartGun.java
> +                                if (loadedBullet.definition.bullet.turnRate > 0) {
i know that ive contemplated making a shotgun with turnrate pellets. and naomi had too

2022-08-13 08:43 UTC, LauraDarkez commented on src/main/java/minecrafttransportsimulator/entities/instances/PartGun.java
> +                bulletVelocity.rotate(firingSpreadRotation);
okay now that ive seen this part of the git i know what to respond to. personally when i was trying to explain in #general, i tried to explain that the pelletSpreadFactor should ONLY be used when pellets > 0, and should NOT use bulletSpreadFactor. seems that was lost in translation somewhere

2022-08-13 13:34 UTC, LauraDarkez commented on src/main/java/minecrafttransportsimulator/entities/instances/PartGun.java
> +                bulletVelocity.rotate(firingSpreadRotation);
even though it could be accepted, one big issue is that it sends pellets flying in random directions but with a randomized overall vector, in reality i dont think this should be the case. it should randomly distribute the pellets but it should do so with a constant overall straight-forward direction. so sometimes pellets will cluster to the left but most of the time itll be a relative spread.

2022-08-13 15:08 UTC, DonBruce64 commented on src/main/java/minecrafttransportsimulator/entities/instances/PartGun.java
> +                bulletVelocity.rotate(firingSpreadRotation);
By the effect of randomness, and the sheer amount of pellets, spread should be fairly uniform.  @ktokto313 it has been decided that the spread needs to be cumulative.  So you'll need to add both those random X and Z components and do a single rotation operation on them, rather than doing two, one after the other, as it will return bad values.

2022-08-13 15:40 UTC, DonBruce64 requested changes

2022-08-13 15:40 UTC, DonBruce64 commented on src/main/java/minecrafttransportsimulator/entities/instances/PartGun.java
> +                firingSpreadRotation.angles.set((Math.random() - 0.5F) * (definition.gun.bulletSpreadFactor + loadedBullet.definition.bullet.pelletSpreadFactor), (Math.random() - 0.5F) * (definition.
Since these are factors, they should multiply, not add.  But watch out for one or the other being 0.

2022-08-13 15:40 UTC, DonBruce64 commented on src/main/java/minecrafttransportsimulator/entities/instances/PartGun.java
>              if (definition.gun.bulletSpreadFactor > 0) {
This only lets the spread activate if the gun has a spread factor.  If the gun doesn't, but the bullet does, this code won't run, despite it needing to.

2022-08-13 15:43 UTC, ktokto313 commented on src/main/java/minecrafttransportsimulator/entities/instances/PartGun.java
> +                firingSpreadRotation.angles.set((Math.random() - 0.5F) * (definition.gun.bulletSpreadFactor + loadedBullet.definition.bullet.pelletSpreadFactor), (Math.random() - 0.5F) * (definition.
It's basically (Math.random() - 0.5d) * bulletSpreadFactor + (Math.random() - 0.5d) * pelletSpreadFactor, i just reduce it

2022-08-13 15:47 UTC, ktokto313 commented
@DonBruce64 the randomization code work alright for me, it's just the reduction of a multiplication, the condition to run the randomization code has been fixed

2022-08-13 18:02 UTC, DonBruce64 commented on src/main/java/minecrafttransportsimulator/entities/instances/PartGun.java
> +                firingSpreadRotation.angles.set((Math.random() - 0.5F) * (definition.gun.bulletSpreadFactor + loadedBullet.definition.bullet.pelletSpreadFactor), (Math.random() - 0.5F) * (definition.
Apparently, I'm the one who can't do math today...

2022-08-13 18:03 UTC, DonBruce64 approved these changes

2022-08-13 18:03 UTC, merged