Added the ability to control part permanent-ness
DonBruce64/MinecraftTransportSimulator pull request #1390
Opened 2022-10-22 23:29 UTC by DrprofLuigi

Also fixed normalized wheel rotation, and modified the engine_piston variable to be compliant as per #1356.

2022-10-24 02:42 UTC, DonBruce64 requested changes

2022-10-24 02:42 UTC, DonBruce64 commented on mccore/src/main/java/minecrafttransportsimulator/entities/components/AEntityF_Multipart.java
> +            for (List<String> variableList : partDef.lockingVariables) {
Looking at this, I only see this variable being different vs the linkedVariables, plus the default.  In this case, the better option is to take the areVaraiblesBlocking function and add the variableList as a paramter so they run off the same code.  Helps if something borks.  As to your defaultValue, that doesn't need to be in here, as you should first check if lockingVariables == null before calling this method, and if it is, just use the default.  I can help clarify, but I say this given what I had to do with the AnimationSwitchbox code.

2022-10-24 02:42 UTC, DonBruce64 commented on mccore/src/main/java/minecrafttransportsimulator/entities/instances/APart.java
> +        isPermanent = areVariablesLocking(placementDefinition, InterfaceManager.clientInterface.getClientPlayer(),placementDefinition.isPermanent);
`InterfaceManager.clientInterface.getClientPlayer(`  BAD.  this can't run on the server.  You don't need the player anyways in the code function either.  Though I see you left that since the player was in the linkedVariables code.

2022-10-24 02:42 UTC, DonBruce64 commented on mccore/src/main/java/minecrafttransportsimulator/entities/instances/PartEngine.java
> +            //double shaftRotation = (offset + getEngineRotation(partialTicks)) - ((360D * camMultiplier) * Math.floor((offset + getEngineRotation(partialTicks)) / (360D * camMultiplier)));
Code not do code here.

2022-10-24 02:42 UTC, DonBruce64 commented on mccore/src/main/java/minecrafttransportsimulator/entities/instances/PartGroundDevice.java
> +            	return vehicleOn != null ? Math.floorMod(Math.round(vehicleOn.speedFactor * (prevAngularPosition + (angularPosition - prevAngularPosition) * partialTicks) * 3600), 3600) / 10D : 0;
You shouldn't have to round anything here....?  If it works, it works, but I think there's bad maths here somewhere.  Normalization never requires rounding.

2022-10-25 23:25 UTC, DrprofLuigi commented on mccore/src/main/java/minecrafttransportsimulator/entities/instances/PartGroundDevice.java
> +            	return vehicleOn != null ? Math.floorMod(Math.round(vehicleOn.speedFactor * (prevAngularPosition + (angularPosition - prevAngularPosition) * partialTicks) * 3600), 3600) / 10D : 0;
Math.floorMod told me it needed integers. Plus making it tenths makes it easier for clamping which is one of the reasons this was added. Though it may be better to have a piston-like version in the future.

Math.floorMod is needed because it allows for the modulo to work as expected with negative values.

2022-10-25 23:26 UTC, DrprofLuigi commented on mccore/src/main/java/minecrafttransportsimulator/entities/instances/PartEngine.java
> +            //double shaftRotation = (offset + getEngineRotation(partialTicks)) - ((360D * camMultiplier) * Math.floor((offset + getEngineRotation(partialTicks)) / (360D * camMultiplier)));
I removed that, I kept it in accidentally.

2022-10-26 00:33 UTC, DrprofLuigi commented on mccore/src/main/java/minecrafttransportsimulator/entities/components/AEntityF_Multipart.java
> +            for (List<String> variableList : partDef.lockingVariables) {
I combined them into `isVariableListTrue`, see my notes in the commit for details. It should be satisfactory, let me know if there are issues.

2022-10-26 00:34 UTC, DrprofLuigi commented on mccore/src/main/java/minecrafttransportsimulator/entities/instances/APart.java
> +        isPermanent = areVariablesLocking(placementDefinition, InterfaceManager.clientInterface.getClientPlayer(),placementDefinition.isPermanent);
I removed it from the combined function `isVariableListTrue` since `player` wasn't used in the function anyway.

2022-10-26 13:01 UTC, DonBruce64 commented on mccore/src/main/java/minecrafttransportsimulator/entities/components/AEntityF_Multipart.java
> +            for (List<String> variableList : partDef.lockingVariables) {
Code looks fine for that.  Though the auto-build-checker script is saying that you missed a function call?  Or is it just obsolete?
`/java/minecrafttransportsimulator/entities/instances/APart.java:424: error: cannot find symbol
        return !entityOn.areVariablesBlocking(placementDefinition, InterfaceManager.clientInterface.getClientPlayer());`

2022-10-26 22:42 UTC, DrprofLuigi commented on mccore/src/main/java/minecrafttransportsimulator/entities/components/AEntityF_Multipart.java
> +            for (List<String> variableList : partDef.lockingVariables) {
I guess I missed that one, it's fixed now.

2022-10-26 23:05 UTC, merged