Added Screwdriver Item
DonBruce64/MinecraftTransportSimulator pull request #1393
Opened 2022-10-28 02:34 UTC by DrprofLuigi

A Screwdriver is simply a mutually exclusive wrench that can only remove parts.

When a part has `mustBeRemovedByScrewdriver` in its generic section it can only be removed by a screwdriver. Perfect for things like hubcaps where you may want to remove the wheel as an assembly when paired with `allowParentRemoval`.

This _should_ add a screwdriver item to the MTS core mod. It's even red!

2022-10-28 03:54 UTC, DonBruce64 requested changes

2022-10-28 03:54 UTC, DonBruce64 commented on mccore/src/main/java/minecrafttransportsimulator/jsondefs/JSONPart.java
> +        @JSONDescription("If true, this part will be able to be removed by hand and without a wrench.  This also bypasses owner requirements (but not vehicle locking).  Useful for small parts like lu
Description is incorrect.

2022-10-28 03:54 UTC, DonBruce64 commented on mccore/src/main/java/minecrafttransportsimulator/entities/instances/APart.java
> +        	//If we are holding a screwdriver, remove the interaction boxes so they don't get in the way.
This comment doesn't match the logic.

2022-10-28 03:54 UTC, DonBruce64 commented on mccore/src/main/java/minecrafttransportsimulator/entities/instances/APart.java
> +            //If we are holding a wrench, remove the interaction boxes so they don't get in the way.
But you aren't holding a wrench according to this `if` statement.

2022-10-28 03:54 UTC, DonBruce64 commented on mccore/src/main/java/minecrafttransportsimulator/entities/instances/APart.java
> +        	for (APart childPart : parts) {
I'm not sure if you need this check.  This check was designed to prevent removal of parts with parts on them.  Pretty sure screwdriverable parts won't have parts on them themselves?

2022-10-28 03:54 UTC, DonBruce64 commented on mccore/src/main/java/minecrafttransportsimulator/entities/instances/APart.java
> +        if (world.isClient() && InterfaceManager.clientInterface.getClientPlayer().isHoldingItemType(ItemComponentType.SCREWDRIVER)) {
You could probably put this under the same if-block as the above.  First check if on client, then check if screwdriver or wrench (store as boolean), then check either boolean, and run common logic.  Cleaner than two individual code blocks with same code.

2022-10-28 03:54 UTC, DonBruce64 commented on mccore/src/main/java/minecrafttransportsimulator/items/instances/ItemItem.java
> +	                                if (!part.isPermanent && part.isValid && part.definition.generic.mustBeRemovedByScrewdriver) {
Given how this seems to be the only code difference between these blocks, what you should do is combine the case statements.  You can do this by writing:
```
case WRENCH:
case SCREWDRIVER: {
//lotta code
}
```

2022-10-29 01:18 UTC, DrprofLuigi commented on mccore/src/main/java/minecrafttransportsimulator/jsondefs/JSONPart.java
> +        @JSONDescription("If true, this part will be able to be removed by hand and without a wrench.  This also bypasses owner requirements (but not vehicle locking).  Useful for small parts like lu
Fixed

2022-10-29 01:19 UTC, DrprofLuigi commented on mccore/src/main/java/minecrafttransportsimulator/entities/instances/APart.java
> +        	for (APart childPart : parts) {
They could, I have some that do.

2022-10-29 01:21 UTC, DrprofLuigi commented on mccore/src/main/java/minecrafttransportsimulator/items/instances/ItemItem.java
> +	                                if (!part.isPermanent && part.isValid && part.definition.generic.mustBeRemovedByScrewdriver) {
The idea here was to leave it open for expansion in the future, so the screwdriver could have other uses. But they could be combined if you don't see that happening.

2022-10-30 22:27 UTC, DonBruce64 requested changes

2022-10-30 22:27 UTC, DonBruce64 commented on mccore/src/main/java/minecrafttransportsimulator/entities/instances/APart.java
> +        if (world.isClient() && (InterfaceManager.clientInterface.getClientPlayer().isHoldingItemType(ItemComponentType.WRENCH) || InterfaceManager.clientInterface.getClientPlayer().isHoldingItemType
Good programming practice says that if you run a function twice in the same block, you should store the result.
Please add
 `boolean isHoldingWrench = InterfaceManager.clientInterface.getClientPlayer().isHoldingItemType(ItemComponentType.WRENCH)`

And the same for screwdriver, and use those booleans.  This code runs every tick, so parsing the player's held item multiple times will generate lag.  Even more speedy, one should probably get the player themselves as `player` from the first methods.

2022-10-30 22:27 UTC, DonBruce64 commented on mccore/src/main/java/minecrafttransportsimulator/items/instances/ItemItem.java
> +	                                if (!part.isPermanent && part.isValid && part.definition.generic.mustBeRemovedByScrewdriver) {
I would say let's code for today.  what I don't like is having two code bits that do the same thing.  That's a recipe for getting one out of whack with the other when changing one.  The paint gun vis-a-vis the crafting GUI is a perfect example.

2022-11-10 06:11 UTC, DrprofLuigi commented on mccore/src/main/java/minecrafttransportsimulator/entities/instances/APart.java
> +        if (world.isClient() && (InterfaceManager.clientInterface.getClientPlayer().isHoldingItemType(ItemComponentType.WRENCH) || InterfaceManager.clientInterface.getClientPlayer().isHoldingItemType
Done

2022-11-12 20:17 UTC, DonBruce64 requested changes

2022-11-12 20:17 UTC, DonBruce64 commented on mccore/src/main/java/minecrafttransportsimulator/items/instances/ItemItem.java
> +	                                if (!part.isPermanent && part.isValid && part.definition.generic.mustBeRemovedByScrewdriver) {
Conversation not resolved.  Request code today be combined.  Can talk about splitting at a later time.

2022-11-13 02:32 UTC, DrprofLuigi commented on mccore/src/main/java/minecrafttransportsimulator/items/instances/ItemItem.java
> +	                                if (!part.isPermanent && part.isValid && part.definition.generic.mustBeRemovedByScrewdriver) {
Done, sorry I missed your reply

2022-11-13 02:35 UTC, DrprofLuigi commented on mccore/src/main/java/minecrafttransportsimulator/entities/instances/APart.java
> +        if (world.isClient() && (InterfaceManager.clientInterface.getClientPlayer().isHoldingItemType(ItemComponentType.WRENCH) || InterfaceManager.clientInterface.getClientPlayer().isHoldingItemType
For some reason doing this causes a crash on startup.

```
    	boolean isHoldingWrench = InterfaceManager.clientInterface.getClientPlayer().isHoldingItemType(ItemComponentType.WRENCH);
    	boolean isHoldingScrewdriver = InterfaceManager.clientInterface.getClientPlayer().isHoldingItemType(ItemComponentType.SCREWDRIVER);

        //If we are holding a screwdriver or wrench, run these checks to remove hitboxes if needed.
        if (world.isClient() && (isHoldingWrench || isHoldingScrewdriver)) {
            //If we are holding a wrench and the part requires a screwdriver, remove interaction boxes so they don't get in the way and vice versa.
            if ((isHoldingWrench && definition.generic.mustBeRemovedByScrewdriver) || (isHoldingScrewdriver && !definition.generic.mustBeRemovedByScrewdriver)) {
                allInteractionBoxes.removeAll(interactionBoxes);
                return;
            }
            //If we are holding a wrench or screwdriver, and the part has children, don't add the interaction boxes.  We can't wrench those parts.
            //The only exceptions are parts that have permanent-default parts on them. or if they specifically don't block subpart removal.  These can be removed.
            //Again, this only applies on clients for that client player.
        	for (APart childPart : parts) {
                if (!childPart.isPermanent && !childPart.placementDefinition.allowParentRemoval) {
                    allInteractionBoxes.removeAll(interactionBoxes);
                    return;
                }
            }
        }
```

But if I bypass the `isHoldingWrench` and `isHoldingScrewdriver` initialization, setting them to true, or embedding them within the checks it works fine.

2022-11-13 19:54 UTC, DonBruce64 commented on mccore/src/main/java/minecrafttransportsimulator/entities/instances/APart.java
> +        if (world.isClient() && (InterfaceManager.clientInterface.getClientPlayer().isHoldingItemType(ItemComponentType.WRENCH) || InterfaceManager.clientInterface.getClientPlayer().isHoldingItemType
Yeah, you're not allowed to check the client interface on the server, so it won't work the first way.  You first should check if the world is client-side, then do the code to get the wrench or screwdriver state, and check that.  So do

if(isClient){
  bool hasScrewdriveR = condition1
  bool hasWrench = condition2
  if(hasScrewdriver || hasWrench){
      do code
  }
}

2022-11-29 01:58 UTC, DrprofLuigi commented on mccore/src/main/java/minecrafttransportsimulator/entities/instances/APart.java
> +        if (world.isClient() && (InterfaceManager.clientInterface.getClientPlayer().isHoldingItemType(ItemComponentType.WRENCH) || InterfaceManager.clientInterface.getClientPlayer().isHoldingItemType
Done! Hopefully this can still be merged. If not, I'll just redo it.

2022-11-29 03:01 UTC, DonBruce64 commented on mccore/src/main/java/minecrafttransportsimulator/entities/instances/APart.java
> +        if (world.isClient() && (InterfaceManager.clientInterface.getClientPlayer().isHoldingItemType(ItemComponentType.WRENCH) || InterfaceManager.clientInterface.getClientPlayer().isHoldingItemType
The only thing that Git doesn't like is the ItemItem file, because I fixed the GUIs not opening right, and that mucks with the wrench-item code.  So if you can re-check-out the file on your end, then apply your changes on-top, it should merge.

2022-12-24 21:56 UTC, closed without merging