sound config
DonBruce64/MinecraftTransportSimulator pull request #1409
Opened 2022-11-05 08:42 UTC by muwwy

Adding new features to the sound config:
- Randomization of sounds
- Setting the range for sound playback
- Doppler pitch effect switch.

Example:
"sounds": [
      {
        "name": "id:shot",
        "activeAnimations": [...],
        "forceSound": true,
        "minDistance": 2,
        "maxDistance": 32,
        "dopplerPitch": true,
        "randomSounds":["id:shot2","id:shot3","id:shot4"]
      }
    ]

2022-11-05 08:53 UTC, DonBruce64 requested changes

2022-11-05 08:53 UTC, DonBruce64 commented on mccore/src/main/java/minecrafttransportsimulator/jsondefs/JSONSound.java
> +    public double maxDistance = 64.0;
Does this match vanilla sound distances?  It should, as this looks to overwrite JSONs that do not define these parameters.  Also, please verify that these defaults are applied when exporting JSONs and when parsing them.  To my recollection, variables here are overwitten with their defaults (0, false) when parsing JSON.  However, that may not be the case.

2022-11-05 08:53 UTC, DonBruce64 commented on mcinterfaceforge1122/src/main/java/mcinterface1122/InterfaceSound.java
> +                Collections.shuffle(sounds);
One shouldn't need to duplicate, shuffle, and get the first index of the list.  Rather, just call Math.Random to get a random number, and multiply it by the total number of random sounds.  Then floor the number to remove the decimal, and use that number to get the index in the random sound list.  Far quicker in execution.

2022-11-05 08:53 UTC, DonBruce64 commented on mccore/src/main/java/minecrafttransportsimulator/jsondefs/JSONSound.java
> +    public boolean dopplerPitch = true;
Normally, for IV things, we go with a "change this to change the default behavior" approach.  It makes it easier for Pack Authors to understand updates.  For this, I ask that it is changed to "blockDoppler" and inverted logic.  As currently, all sounds have doppler.  So to ensure that PAs don't have to change their JSONs, the new parameter should have all sounds have doppler.

2022-11-05 08:53 UTC, DonBruce64 commented on mccore/src/main/java/minecrafttransportsimulator/sound/SoundInstance.java
> -    public final String soundName;
This should still be final as it should not be able to be modified after starting the sound (that will cause the sound-system to be de-synced).  Please move the code to choose a random sound into the constructor here.

2022-11-05 08:54 UTC, DonBruce64 commented
Good first PR, but a few comments on logic.  I can for sure see some good use out of this.

2022-11-05 09:01 UTC, dldev32 commented
I will update the wiki article about this.

2022-11-05 09:49 UTC, Ilya-torshov commented
Doppler effect should be opt-out instead of opt-in by the way

2022-11-05 10:40 UTC, muwwy reviewed
2.0

2022-11-05 21:50 UTC, DonBruce64 commented
> Doppler effect should be opt-out instead of opt-in by the way

I mentioned that in the change requests.  I gotchu mate.

2022-11-05 21:56 UTC, DonBruce64 requested changes
One change requested, one food for thought that does not require changes (unless you want to make them)

2022-11-05 21:56 UTC, DonBruce64 commented on mcinterfaceforge1122/src/main/java/mcinterface1122/InterfaceSound.java
> +                    if (sound.soundDef != null && sound.soundDef.looping && !sound.entity.equals(player.getEntityRiding()) && !sound.soundDef.blockDoppler) {
You'll want to check for the doppeler first (well, after making sure soundDef is not null).  This is because it won't do you any good to check looking or what the player is riding if the sound doesn't have doppler to begin with.  That's just extra code to run.

2022-11-05 21:56 UTC, DonBruce64 commented on mccore/src/main/java/minecrafttransportsimulator/entities/components/AEntityD_Definable.java
> +                        if (distance <= soundDef.maxDistance && distance >= soundDef.minDistance) {
I noticed that this only blocks the sound from playing.  Should it also stop playing sounds outside the range?  Not required for me to approve this PR.  But if you want that functionality, it's easy enough to add since there's already logic to check if the should should be playing at all.  Just make that boolean false if you have a range and you're out if it.

2022-11-06 04:40 UTC, muwwy commented on mccore/src/main/java/minecrafttransportsimulator/entities/components/AEntityD_Definable.java
> +                        if (distance <= soundDef.maxDistance && distance >= soundDef.minDistance) {
I don't think it's necessary to stop sounding outside.
The logic is simple, this function is needed for the variability of sound, for example, if a gun is fired near there will be one sound, and if in the distance, then a muffled sound.

I would really like you to approve this PR, because we need this functionality.

2022-11-06 05:38 UTC, dldev32 commented
Without these requirements, the PR will not be approved, do I understand correctly?

2022-11-06 09:10 UTC, DonBruce64 commented on mccore/src/main/java/minecrafttransportsimulator/entities/components/AEntityD_Definable.java
> +                        if (distance <= soundDef.maxDistance && distance >= soundDef.minDistance) {
That is fine.  If you don't see a reason to stop the sound, then I don't mind.  Folks can submit that as a bug later if they see it as one.

PR will get approved once the first-comment about order of operations is addressed.  That's the last outstanding item.

2022-11-06 09:10 UTC, DonBruce64 commented
> 

You understand incorrectly.  See my notes on that requirement.

2022-11-06 10:09 UTC, muwwy commented on mccore/src/main/java/minecrafttransportsimulator/entities/components/AEntityD_Definable.java
> +                        if (distance <= soundDef.maxDistance && distance >= soundDef.minDistance) {
Can this be considered a solution to our problem ? (even though it looks like a crutch)
![image](https://user-images.githubusercontent.com/49564303/200164562-fbfe04de-786b-4e81-96a4-503b1625c71b.png)
![image](https://user-images.githubusercontent.com/49564303/200164601-511eb344-6405-42b6-bfc5-421c027df4ca.png)
In addition, when checking, it turned out that variables are assigned a value from JSON during export and parsing. So it really worked last time, and now.

2022-11-06 10:25 UTC, DonBruce64 commented on mccore/src/main/java/minecrafttransportsimulator/entities/components/AEntityD_Definable.java
> +                        if (distance <= soundDef.maxDistance && distance >= soundDef.minDistance) {
Oh no, I meant the code in InterfaceSound for the doppler effect, not that code.  There's also no way that you'll ever have 0 there, since you set that value to 64 manually if it's not present (is 0)?

2022-11-06 10:34 UTC, muwwy commented on mccore/src/main/java/minecrafttransportsimulator/entities/components/AEntityD_Definable.java
> +                        if (distance <= soundDef.maxDistance && distance >= soundDef.minDistance) {
my bad, I did something incomprehensible..

2022-11-06 10:41 UTC, muwwy commented on mccore/src/main/java/minecrafttransportsimulator/entities/components/AEntityD_Definable.java
> +                        if (distance <= soundDef.maxDistance && distance >= soundDef.minDistance) {
Can I leave it as it was?
Because the usual values that I set manually do not affect the values in JSON in any way
![image](https://user-images.githubusercontent.com/49564303/200166110-f2b96073-030b-4837-93a8-5eb88aa32283.png)

2022-11-06 14:35 UTC, DonBruce64 commented on mccore/src/main/java/minecrafttransportsimulator/entities/components/AEntityD_Definable.java
> +                        if (distance <= soundDef.maxDistance && distance >= soundDef.minDistance) {
My bad, I see what this was about.  Go ahead and put it back the way you have.

2022-11-06 14:35 UTC, DonBruce64 commented on mccore/src/main/java/minecrafttransportsimulator/entities/components/AEntityD_Definable.java
> +                        if (distance <= soundDef.maxDistance && distance >= soundDef.minDistance) {
Actually, it looks like it is that way.  Marking resolved.

2022-11-06 14:40 UTC, DonBruce64 commented
Once you check the max sound distance, I'm good.  I want to make sure that no existing sounds play when you are more than 64 blocks away, since that will confuse PAs who had their sounds play that far previously.  Horns and sirens and engines are the ones I would check.

Alternately, you could just check if both are 0, and if so, ignore distance entirely.  TBH, that's a bit cleaner since it won't cause a new JSON parameter in every JSON.  But I'm not married to the idea so I won't force you to do that.

2023-01-02 00:53 UTC, merged