Made it so an empty default part string won't display an error message.
DonBruce64/MinecraftTransportSimulator pull request #1420
Opened 2022-11-10 06:02 UTC by DrprofLuigi

Useful when you want to intentionally spawn no part in `conditionalDefaultParts`

2022-11-10 17:33 UTC, DonBruce64 commented
But why would you want to spawn no part?  You should just not include it in the conditionalDefalts?

2022-11-11 01:06 UTC, DrprofLuigi commented
```			"conditionalDefaultParts": {
				"spare_hubcap_dish"="unuparts:unuparts_part_unu_hubcap_standard_dish",
				"spare_hubcap_turbine"="unuparts:unuparts_part_unu_hubcap_standard_turbine",
				"part_isspare"="",
				"hubcap_dish"="unuparts:unuparts_part_unu_hubcap_standard_dish",
				"hubcap_turbine"="unuparts:unuparts_part_unu_hubcap_standard_turbine"
			}```
			
The vehicle as a whole has the constant to define the hubcap, but I don't want a hubcap to spawn when it is a spare tire (unless it is specifically overridden). This is also why I added the `part_isspare` variable.

2022-11-12 20:20 UTC, DonBruce64 requested changes

2022-11-12 20:20 UTC, DonBruce64 commented on mccore/src/main/java/minecrafttransportsimulator/entities/components/AEntityF_Multipart.java
> +            if (!partName.isEmpty()) {
Request that rather than checking down here after the code has failed, you just don't run the addDefaultPart method at all if partName is empty.  If you know it's empty, don't even try to add the default part.

2022-11-13 04:34 UTC, DrprofLuigi commented on mccore/src/main/java/minecrafttransportsimulator/entities/components/AEntityF_Multipart.java
> +            if (!partName.isEmpty()) {
Done, honestly I feel a bit dumb for doing what I did lol

2022-11-13 19:55 UTC, merged