Fix Tracking bug
DonBruce64/MinecraftTransportSimulator pull request #1501
Opened 2023-01-09 05:57 UTC by conman180

Added .copy() to function as old function was moving the target's engine part out to the predicted impact point rather than the bullet just aiming there.
Bug found by VEB's Wartich.

2023-01-09 17:17 UTC, DonBruce64 commented
Are you sure this is what fixes it?  Looking at the old code, I see no modification being made to the engine's position.  You set the target to the value of the engine's position, and modify the target vector, but you never modify the engine's position vector.

2023-01-11 22:31 UTC, conman180 commented
Just figured out this did not solve the issue. will commit changes once confirmed solution is found.

2023-01-12 13:18 UTC, DonBruce64 requested changes

2023-01-12 13:18 UTC, DonBruce64 commented on mccore/src/main/java/minecrafttransportsimulator/entities/instances/EntityBullet.java
> +                targetVector.set(targetPosition.copy().addScaled(engineTargeted.vehicleOn.motion, (engineTargeted.vehicleOn.speedFactor/ 20D/10D) * ticksToTarget)).subtract(position).reOrigin(orienta
You don't need to copy the targetPosition here.  I know why you're doing it: because if you don't, and you addScaled to it, then you modify that vector.  But what you should do is set the targetVector to targetPosition, then do the modifications to targetVector itself.

2023-01-13 19:46 UTC, conman180 commented
That should fix the lead calculation. Or are there any other changes you request?

2023-01-13 23:39 UTC, merged