Various things
DonBruce64/MinecraftTransportSimulator pull request #1527
Opened 2023-02-01 20:18 UTC by conman180

For some reason my IDE did a thing when merging that copies commits that have already been merged. Other changest are
-a couple typo fixes
-Mic's crate explosiveness calculations
-Update bullets to apply gravity and slowdown forces before a motor burns s well as after
-moved gravitational velocity over to bullet jsons rather than the gun.
-fix the math for radar contact bearing.

2023-02-02 18:49 UTC, DonBruce64 requested changes

2023-02-02 18:49 UTC, DonBruce64 commented on mccore/src/main/java/minecrafttransportsimulator/jsondefs/JSONBullet.java
> +        @JSONDescription("How much velocity, each tick, should be added in the -Y direction.  Used to make bullets travel in arcs.")
Make sure the wiki gets updated, and I'm good with this.

2023-02-02 18:49 UTC, DonBruce64 commented on mccore/src/main/java/minecrafttransportsimulator/jsondefs/JSONPart.java
> -        @JSONDescription("How much velocity, each tick, should be added in the -Y direction.  Used to make bullets travel in arcs.")
Same thing about the wiki.

2023-02-02 18:49 UTC, DonBruce64 commented on mccore/src/main/java/minecrafttransportsimulator/entities/instances/EntityBullet.java
> +        if (ticksExisted > definition.bullet.burnTime || ticksExisted < definition.bullet.accelerationDelay) {
Good catch!

2023-02-02 18:49 UTC, DonBruce64 commented on mccore/src/main/java/minecrafttransportsimulator/entities/instances/EntityBullet.java
> +                if ((gun.definition.gun.targetType == TargetType.ALL && engineTargeted != null) || gun.definition.gun.targetType == TargetType.AIRCRAFT || gun.definition.gun.targetType == TargetType.
This is likely not what you want.  It doesn't assure that engineTargeted is no longer null.  So if you don't have an engine targeted, but you're an AIRCRAFT or a GROUND type bullet, you'll execute this code, and crash when you try to set the targetVector since engineTargeted is null.

2023-02-02 18:49 UTC, DonBruce64 commented on mccore/src/main/java/minecrafttransportsimulator/entities/instances/EntityBullet.java
> +                } else if ((gun.definition.gun.targetType == TargetType.ALL && externalEntityTargeted != null) || gun.definition.gun.targetType == TargetType.SOFT) {
Same comment as above, just for externalEntityTargeted.

2023-02-03 01:09 UTC, conman180 commented on mccore/src/main/java/minecrafttransportsimulator/jsondefs/JSONBullet.java
> +        @JSONDescription("How much velocity, each tick, should be added in the -Y direction.  Used to make bullets travel in arcs.")
Wiki will be updated.

2023-02-03 05:05 UTC, merged