A few things cant remember all of them.
DonBruce64/MinecraftTransportSimulator pull request #1546
Opened 2023-02-25 05:16 UTC by conman180

small fixes and additions for things.

2023-02-25 20:22 UTC, DonBruce64 requested changes

2023-02-25 20:22 UTC, DonBruce64 commented on mccore/src/main/java/minecrafttransportsimulator/packloading/LegacyCompatSystem.java
> +            definition.general.radarRange = 512;
You probably don't want this here.  This will only work on older JSONs.  If someone has a newer JSON where emptyMass is defined in the motorized section per standards, it won't auto-add your radar parameters.  You will want to check if they are 0 outside this if statement.

2023-02-25 20:22 UTC, DonBruce64 commented on mccore/src/main/java/minecrafttransportsimulator/entities/components/AEntityD_Definable.java
> +                Point3D searchVector = new Point3D(0, 0, definition.general.radarRange).rotate(orientation);
Since you're iterating over all vehicles, you want to make searchVector once, outside the loop, then set the value of it inside the loop.  Far faster than creating a new object (or two, given there's another Point3D in  here) each vehicle..

2023-02-25 20:22 UTC, DonBruce64 commented on mccore/src/main/java/minecrafttransportsimulator/entities/components/AEntityD_Definable.java
> +                if (!vehicle.outOfHealth && vehicle != this && (angle < coneAngle && vehicle.position.distanceTo(position) < definition.general.radarRange)) {
Rather than doing distanceTo, there's a function isDistanceToCloserThan for Point3D.  That function is more efficient as it doesn't calculate square roots.  MC does this for most, if not all, of its distance checks, since square roots are CPU intensive.

2023-02-26 02:40 UTC, conman180 commented on mccore/src/main/java/minecrafttransportsimulator/packloading/LegacyCompatSystem.java
> +            definition.general.radarRange = 512;
I put this in the general section that way AA turrets and the like have the ability to make use of the radar. To my knowledge I didnt do anything to emptyMass.

2023-02-26 02:42 UTC, conman180 commented on mccore/src/main/java/minecrafttransportsimulator/packloading/LegacyCompatSystem.java
> +            definition.general.radarRange = 512;
retracted comment. understand what you mean now.

2023-02-26 02:49 UTC, conman180 commented on mccore/src/main/java/minecrafttransportsimulator/packloading/LegacyCompatSystem.java
> +            definition.general.radarRange = 512;
commit on this removes legacy compat as it auto-reverts to zero and doesnt crash if not included in the json.

2023-02-27 22:53 UTC, merged