Allowed manual defintion of the groundDeviceBox
DonBruce64/MinecraftTransportSimulator pull request #1621
Opened 2023-05-03 05:19 UTC by DrprofLuigi

Fixes #1484

2023-05-03 05:21 UTC, DrprofLuigi commented
This adds a part slot definition of `groundDeviceBoxNumber` where you can hard-define the corner the wheel is assigned to.

2023-05-06 15:38 UTC, DonBruce64 requested changes

2023-05-06 15:38 UTC, DonBruce64 commented on mccore/src/main/java/minecrafttransportsimulator/baseclasses/VehicleGroundDeviceBox.java
> +                    if (isFront && ((ground.wheelbasePoint.z > 0 && groundDeviceBoxNumber == 0) || 3 <= groundDeviceBoxNumber)) {
I'm thinking this line isn't right, since it has a <= in it rather than a ==.

2023-05-06 15:38 UTC, DonBruce64 commented on mccore/src/main/java/minecrafttransportsimulator/baseclasses/VehicleGroundDeviceBox.java
> +                    } else if (!isFront && ((ground.wheelbasePoint.z <= 0 && groundDeviceBoxNumber == 0) || (1 <= groundDeviceBoxNumber && groundDeviceBoxNumber <= 2))) {
(1 <= groundDeviceBoxNumber && groundDeviceBoxNumber <= 2)
This just checks if the GDVB is 1 or 2, so a cleaner way of doing this is:
(1 == groundDeviceBoxNumber || groundDeviceBoxNumber == 2)
Same with others.

2023-05-06 15:38 UTC, DonBruce64 commented on mccore/src/main/java/minecrafttransportsimulator/baseclasses/VehicleGroundDeviceBox.java
> +                        } else if (!isLeft && ((ground.wheelbasePoint.x <= 0 && groundDeviceBoxNumber == 0) || groundDeviceBoxNumber == 2)) {
As a general thought though, have you considered an enum for this?  Where you make this a string-based paramter like frontLeft, frontRight, rearLeft, rearRight?  With an enum, you can also add simple functions such as groundDeviceBox.isRight() or .isFront().  It's clearer to the PA since they don't need to remember which number goes to what, and cuts down on these odd equalities.  See ABlockBase.Axis for more details.

2023-05-10 06:52 UTC, DrprofLuigi commented on mccore/src/main/java/minecrafttransportsimulator/baseclasses/VehicleGroundDeviceBox.java
> +                        } else if (!isLeft && ((ground.wheelbasePoint.x <= 0 && groundDeviceBoxNumber == 0) || groundDeviceBoxNumber == 2)) {
I modified it to use a string definition. I'm not sure how to use enum in this context.

2023-05-12 22:28 UTC, DonBruce64 commented on mccore/src/main/java/minecrafttransportsimulator/baseclasses/VehicleGroundDeviceBox.java
> +                        } else if (!isLeft && ((ground.wheelbasePoint.x <= 0 && groundDeviceBoxNumber == 0) || groundDeviceBoxNumber == 2)) {
@DrprofLuigi Changed to use enums.  You'll wanna test my logic to be sure it meets your needs.  I added center-wheels, since that's required for things like the Trio and the Auroras for their front and rear wheels respectively which are both left and right wheels.

2023-05-27 06:59 UTC, DrprofLuigi commented
Is there anything else that needs to be done on this (i.e. do I need to go in and to the internal definitions to use the enum values)?

2023-05-28 04:28 UTC, DonBruce64 commented
I've changed all the code to work in both files, but you should probably test it to make sure it does what you want it to still and I didn't screw it up.

2023-05-28 22:45 UTC, DrprofLuigi commented
I can confirm it works. I'll update the wiki when this PR is merged.

2023-05-29 00:35 UTC, merged

2023-05-29 00:35 UTC, DonBruce64 commented
Merged and ready for wiki entry.