Allowed for more complex VM Math
DonBruce64/MinecraftTransportSimulator pull request #1640
Opened 2023-05-27 06:57 UTC by DrprofLuigi

This PR adds trig functions as well as square rooting and division to VM math. This also adds an 'invert' boolean field to animations (that is only used in VMs for now)

In the following expressions, 'MV' is `modifiedValue` or the 'running total' of the VM. `V` is the input variable value, `[X, Y, Z]` is the axis, and `[x, y, z]` is the centerPoint.

If a translation has an inversion tag, then the output is modified as shown below:

The 'multiplication slot' goes from `MV * (X * V)` to `MV * V^(1/X)` (This allows for multiple roots, not just square roots)

The 'addition slot' goes from `MV + (Y * V)` to `MV / (Y * V)`

The 'set value' slot is unchanged.

The trig functions utilize the 'rotation' animationType.

The output is simply:

`MV * (Xsin(V + x) Ycos(V + y) + Ztan(V + z))` (inputs in degrees)

When inverted, the trig functions are swapped to their inverses (sine becomes arcsine, etc.).

There are internal conversions in the code to keep radians in their place.

This picture shows the test values, and I tested it fairly thoroughly:
![2023-05-26_23 32 00](https://github.com/DonBruce64/MinecraftTransportSimulator/assets/36775575/dfa2fed2-cba5-40b1-afe9-c7d80f26104e)

Here are the VMs that produced the above output:
```		{
			"variable": "clock",
			"animations": [
				{
					"animationType": "translation",
					"variable": "unuisbest",
					"axis": [0, 1, 0]
				},
				{
					"animationType": "inhibitor",
					"variable": "clock",
					"clampMin": 1,
					"clampMax": 360
				},
				{
					"animationType": "translation",
					"variable": "unuisbest",
					"axis": [0, 0, 1]
				}
			]
		},
		{
			"variable": "clock_sin",
			"animations": [
				{
					"animationType": "translation",
					"variable": "unuisbest",
					"axis": [0, 0, 1]
				},
				{
					"animationType": "rotation",
					"variable": "clock",
					"centerPoint": [0, 0, 0],
					"axis": [1, 0, 0]
				}
			]
		},
		{
			"variable": "clock_cos",
			"animations": [
				{
					"animationType": "translation",
					"variable": "unuisbest",
					"axis": [0, 0, 1]
				},
				{
					"animationType": "rotation",
					"variable": "clock",
					"centerPoint": [0, 0, 0],
					"axis": [0, 1, 0]
				}
			]
		},
		{
			"variable": "clock2",
			"animations": [
				{
					"animationType": "translation",
					"variable": "unuisbest",
					"axis": [0, 0.01, 0]
				},
				{
					"animationType": "inhibitor",
					"variable": "clock2",
					"clampMin": -1,
					"clampMax": 2
				},
				{
					"animationType": "translation",
					"variable": "unuisbest",
					"axis": [0, 0, -1]
				}
			]
		},
		{
			"variable": "clock2_asin",
			"animations": [
				{
					"animationType": "translation",
					"variable": "unuisbest",
					"axis": [0, 0, 1]
				},
				{
					"animationType": "rotation",
					"variable": "clock2",
					"centerPoint": [0, 0, 0],
					"axis": [1, 0, 0],
					"invert": true
				}
			]
		},
		{
			"variable": "clock2_acos",
			"animations": [
				{
					"animationType": "translation",
					"variable": "unuisbest",
					"axis": [0, 0, 1]
				},
				{
					"animationType": "rotation",
					"variable": "clock2",
					"centerPoint": [0, 0, 0],
					"axis": [0, 1, 0],
					"invert": true
				}
			]
		},
		{
			"variable": "test",
			"animations": [
				{
					"animationType": "translation",
					"variable": "unuisbest",
					"axis": [0, 0, 5]
				}
			]
		},
		{
			"variable": "test2",
			"animations": [
				{
					"animationType": "translation",
					"variable": "unuisbest",
					"axis": [0, 0, 1]
				},
				{
					"animationType": "translation",
					"variable": "test",
					"axis": [2, 0, 0],
					"invert": true
				}
			]
		},
		{
			"variable": "test3",
			"animations": [
				{
					"animationType": "translation",
					"variable": "unuisbest",
					"axis": [0, 0, 1]
				},
				{
					"animationType": "translation",
					"variable": "test",
					"axis": [3, 0, 0],
					"invert": true
				}
			]
		}```

2023-05-27 07:17 UTC, DrprofLuigi commented
After thinking about it for a moment, I realize the 'invert' tag for the translation animation is fairly redundant.

A cleaner way to do it would be to do the following for the translation logic.

If X != 0 and Y !=0, then the output is:

MV * (X * V^Y)

This allows for division by setting Y to -1, and allows for simple squaring and rooting. This should also keep things backwards-compatible because iirc everyone that uses VMs to multiply uses an axis of `[X, 0, 0]` This would eliminate the invert tag from being used in the translation case altogether. 

It is also unlikely that someone would want to do `MV * (X * V^0)` since that is just multiplying by a constant (which could be done easily by just multiplying by a constant-defined variable), so using Y = 0 as a backwards-compatible case shouldn't be an issue. Though I would ask the MTS discord to make sure there aren't any sloppy VM multiplications that may get messed up.

2023-05-28 04:31 UTC, DonBruce64 requested changes

2023-05-28 04:31 UTC, DonBruce64 commented on mccore/src/main/java/minecrafttransportsimulator/entities/components/AEntityD_Definable.java
> +                modifiedValue *= Math.pow(entity.getAnimatedVariableValue(clock, clock.animation.axis.x, partialTicks), clock.animation.axis.y != 0 ? clock.animation.axis.y : 1);
This should be an if check.  Don't run Pow functions if you know you don't need to and will only raise to the power of 1.  Pow functions are a significant overhead and should only be ran when absolutely required.  Same for square root.

2023-05-28 22:48 UTC, DrprofLuigi commented on mccore/src/main/java/minecrafttransportsimulator/entities/components/AEntityD_Definable.java
> +                modifiedValue *= Math.pow(entity.getAnimatedVariableValue(clock, clock.animation.axis.x, partialTicks), clock.animation.axis.y != 0 ? clock.animation.axis.y : 1);
Done

2023-05-29 02:50 UTC, DonBruce64 requested changes

2023-05-29 02:50 UTC, DonBruce64 commented on mccore/src/main/java/minecrafttransportsimulator/jsondefs/JSONAnimationDefinition.java
> +    @JSONDescription("Used for VMs. If true, trig functions will be inverted.")
I noticed that you said invert was redundant.  Is that still the case?  I don't see it used in the code, but I do see it in the JSON here.

2023-05-30 02:02 UTC, DrprofLuigi commented on mccore/src/main/java/minecrafttransportsimulator/jsondefs/JSONAnimationDefinition.java
> +    @JSONDescription("Used for VMs. If true, trig functions will be inverted.")
Inverting for the translation was redundant. It is still necessary for the rotation (trig) case.

It was redundant for the translation case because I had it trigger rooting and division, but with the other exponent method, rooting and division can just be done with an exponent.

2023-05-30 03:30 UTC, merged