Bullets & Guns Stuff
DonBruce64/MinecraftTransportSimulator pull request #1678
Opened 2023-07-05 15:58 UTC by conman180

Ignore commits for the gravity stuff as that was already merged. Don't know why it still shows up here.
First commit: makes it so active guidance bullets have that same search cone as guns do. if the target its tracking goes outside that cone, it loses lock. Also makes a check if terrain is in between bullet and target, allowing for terrain to break said lock as well. may need a little tweaking still but need your help with it.

Second commit: Adds a check for if the gun that has a lock on a target is on a vehicle, if it is, it bases the reference point for animations of of the vehicle pos rather than gun pos. this is to help animations on HUDs stay lined up on larger aircraft.

2023-07-05 16:07 UTC, conman180 commented
Will add those two new json defs for bullets to the wiki once merged.

2023-07-13 02:01 UTC, DonBruce64 requested changes

2023-07-13 02:01 UTC, DonBruce64 commented on mccore/src/main/java/minecrafttransportsimulator/entities/instances/PartGun.java
> +            direction = Math.toDegrees(Math.atan2(-engineTarget.vehicleOn.position.z + (vehicleOn!=null ?vehicleOn.position.z : position.z), -engineTarget.vehicleOn.position.x + (vehicleOn!=null ?veh
You check if the vehicleOn is not null three times.  Better thing to do is make a variable up by double direction called "startPoint" or something and set that to vehicleOn.position or position and reference that variable down here.  Cleaner code.

2023-07-13 02:01 UTC, DonBruce64 commented on mccore/src/main/java/minecrafttransportsimulator/entities/instances/PartGun.java
> +                return entityTarget != null ? (-Math.toDegrees(Math.atan2(-entityTarget.getPosition().y + (vehicleOn!=null ?vehicleOn.position.y : position.y),Math.hypot(-entityTarget.getPosition().z
Same as above comment.

2023-07-13 02:47 UTC, DonBruce64 requested changes

2023-07-13 02:47 UTC, DonBruce64 commented on mccore/src/main/java/minecrafttransportsimulator/entities/instances/PartGun.java
> +        Point3D referencePos = new Point3D();
You don't need to make a new point here though?  You only reference the point you choose in the older version.  So `Point3D referencePos = vehicleOn != null ? vehicleOn.position : position`.  Don't create variables you don't need  if you can just reference existing ones.  `new` makes new variables.

2023-07-13 02:47 UTC, DonBruce64 commented on mccore/src/main/java/minecrafttransportsimulator/entities/instances/PartGun.java
> +            angle = (-Math.toDegrees(Math.atan2(-getLockedOnLeadPoint().y + position.y, Math.hypot(-getLockedOnLeadPoint().z + position.z, -getLockedOnLeadPoint().x + position.x))) + orientation.angl
This also has the multiple != null checks as the other code, please convert to similar style.

2023-07-13 03:00 UTC, merged