Steering QOL improvement (configurable steering centering rate)
DonBruce64/MinecraftTransportSimulator pull request #1736
Opened 2023-12-08 09:25 UTC by BlazeWolf1122

This is a feature ive been wanting for as long as ive used MTS and ive finally been able to uhhh "do it"
I hope this isn't considered "janky" or "bad code", cause it does look a bit out of place when you look at the rest of the surrounding code

2023-12-09 21:11 UTC, DonBruce64 requested changes

2023-12-09 21:11 UTC, DonBruce64 commented on mccore/src/main/java/minecrafttransportsimulator/entities/instances/EntityVehicleF_Physics.java
> +    public static final double RUDDER_DAMPEN_RATE = ConfigSystem.client.controlSettings.steeringReturnRate.value;
This won't do what you want it to do.  This only checks the config once when you boot, and won't check if you change the config mid-game.  What you want to do is not use this variable on client-side control inputs, but leave it for server-side inputs.

2023-12-28 00:45 UTC, DonBruce64 requested changes

2023-12-28 00:45 UTC, DonBruce64 commented on mccore/src/main/java/minecrafttransportsimulator/systems/ControlSystem.java
> +            if (!ControlsKeyboard.CAR_TURN_L.isPressed() && !ControlsKeyboard.CAR_TURN_L.wasPressedLastCall && !ControlsKeyboard.CAR_TURN_R.isPressed() && !ControlsKeyboard.CAR_TURN_R.wasPressedLastC
Very close sir.  I see you have both paramters in the config.  But you don't reference the custom dampen rate here, so I think you want this in this code section?  See how the controlSettings.steeringControlRate.value is used for the increment rate?  You need to feed in your new config rather than the RUDDER_DAMPEN_RATE to make this work.  No if-pressed-checks required.

2024-01-05 00:28 UTC, BlazeWolf1122 commented on mccore/src/main/java/minecrafttransportsimulator/systems/ControlSystem.java
> +            if (!ControlsKeyboard.CAR_TURN_L.isPressed() && !ControlsKeyboard.CAR_TURN_L.wasPressedLastCall && !ControlsKeyboard.CAR_TURN_R.isPressed() && !ControlsKeyboard.CAR_TURN_R.wasPressedLastC
Thanks for letting me know, will try to get to it in a few days

2024-01-18 20:17 UTC, BlazeWolf1122 commented
hello this took far too long but i finally used your advice and updated the PR
this has been haunting me in my dreams

2024-01-18 20:28 UTC, BlazeWolf1122 commented
also im pleasantly surprised that the if-then thing could've simply just been one line
well, i guess you don't know until you know

2024-01-18 23:03 UTC, merged