steeringForceFactor + steeringForceIgnoresSpeed
DonBruce64/MinecraftTransportSimulator pull request #1778
Opened 2024-03-06 22:47 UTC by boot2big

### This PR does four significant things:
- downForce has been renamed to steeringForceFactor, otherwise retaining its same functionality\* _(\*See below)_
- steeringForceIgnoresSpeed, switches handling behavior to ignore the vehicle's current velocity. 
- When above boolean is true, ~~downForce~~ steeringForceFactor directly controls the vehicle's turningForce instead of it being influenced by speed and steeringForceFactor.
- slip_understeer, current steering angle - turningForce (if the vehicle cannot turn at all this returns 1.0, otherwise everything between 0.0)

### But why?
Some pack authors may find the current behavior of downForce/overSteer/underSteer to offer less control over their vehicle's handling than wished. This is especially noticeable because at low speeds, downForce has little to no effect on vehicle handling. However this pull request seeks to alleviate that by retaining this behavior by default whilst offering an alternative.
As ~~downForce~~ steeringForceFactor can be variableModified, this results in more customizable vehicle behavior through the use of clever VMs.

### Other stuff
downForce has technically been deprecated, however it is immediately LC'ed to steeringForceFactor. As there is no change in functionality when steeringForceIgnoresSpeed is false, this has no effect on any packs to my knowledge.
Demonstrational Video

https://github.com/DonBruce64/MinecraftTransportSimulator/assets/53581325/dfe40d9d-b263-4e3a-b672-5b83441816fc

\*sigh\* Point, not ponit.

2024-03-07 16:39 UTC, DonBruce64 requested changes

2024-03-07 16:39 UTC, DonBruce64 commented on mccore/src/main/java/minecrafttransportsimulator/packloading/LegacyCompatSystem.java
> +        //Change downForce's name to steeringForceFactor
You'll want to also set downForce to 0 here to prevent it and steeringForceFactor from showing up in the devmode outputted JSON.

2024-03-07 16:39 UTC, DonBruce64 commented on mccore/src/main/java/minecrafttransportsimulator/entities/instances/EntityVehicleF_Physics.java
> +            case ("slip_understeer"):
This section is a control-flow error.  Though not an obvious one.  If you have a case statement without curly bois {} after it, it only executes the first block of code, then goes on to do other stuff.  So you're just calculating turning force here and returning 0 later on down the line.  Either add curlys, or make it a one-liner like the rest of the entries here.

2024-03-07 16:39 UTC, DonBruce64 commented on mccore/src/main/java/minecrafttransportsimulator/entities/instances/AEntityVehicleD_Moving.java
> +    public float currentSteeringForceIgnoration;
Request name of currentSteeringForceIgnored

2024-03-07 16:39 UTC, DonBruce64 commented on mccore/src/main/java/minecrafttransportsimulator/entities/instances/AEntityVehicleD_Moving.java
> +    protected float getSkiddingForce() {
This should still be private VS protected?

2024-03-07 16:39 UTC, DonBruce64 commented on mccore/src/main/java/minecrafttransportsimulator/entities/instances/AEntityVehicleD_Moving.java
> +    protected double getTurningForce() {
This should still be private VS protected?

2024-03-07 16:39 UTC, DonBruce64 commented on mccore/src/main/java/minecrafttransportsimulator/entities/instances/AEntityVehicleD_Moving.java
> +                return turningForce * (groundVelocity * (currentOverSteer + 1)) * (speedFactor / 0.35D) / 2D;
I see you added currentOverSteer here.  Was this intentional?  I know we already use this value somewhere else given that you didn't add it to the class file, so isn't it doing what it's supposed to somewhere else?

2024-03-07 18:47 UTC, boot2big commented on mccore/src/main/java/minecrafttransportsimulator/packloading/LegacyCompatSystem.java
> +        //Change downForce's name to steeringForceFactor
Ah? I thought this wasn't necessary at first, but now that you point it out that makes sense if I have to define it as deprecated. Thank you!

2024-03-07 18:48 UTC, boot2big commented on mccore/src/main/java/minecrafttransportsimulator/entities/instances/EntityVehicleF_Physics.java
> +            case ("slip_understeer"):
I.. thought it worked when I tested it? It still returned the result from what I could see, but I'll tweak this as advised. :+1:

2024-03-07 18:49 UTC, boot2big commented on mccore/src/main/java/minecrafttransportsimulator/entities/instances/AEntityVehicleD_Moving.java
> +    public float currentSteeringForceIgnoration;
`steeringForceIgnoresSpeed`
Was unsure if `currentSteeringForceIgnoresSpeed` would fit better. EZ change if so

2024-03-07 18:50 UTC, boot2big commented on mccore/src/main/java/minecrafttransportsimulator/entities/instances/AEntityVehicleD_Moving.java
> +    protected float getSkiddingForce() {
That's a mistake on my part in figuring out how to return understeer, my apologies. Will be privated.

2024-03-07 18:51 UTC, boot2big commented on mccore/src/main/java/minecrafttransportsimulator/entities/instances/AEntityVehicleD_Moving.java
> +    protected double getTurningForce() {
_This_ I did intentionally open because that is what gets used in `slip_understeer`. If getTurningForce() is supposed to be private, should I simply make a public variable that returns getTurningForce()?

2024-03-07 18:54 UTC, boot2big commented on mccore/src/main/java/minecrafttransportsimulator/entities/instances/AEntityVehicleD_Moving.java
> +                return turningForce * (groundVelocity * (currentOverSteer + 1)) * (speedFactor / 0.35D) / 2D;
Eeehm, no it is not..? That's another mistake on my part, I haven't the foggiest how that got added. Might've happened while I was crossreferencing a fellow PA's PRs, as the precursor to this request was me trying to rip the code apart to replace it entirely.

2024-03-07 19:29 UTC, DonBruce64 commented on mccore/src/main/java/minecrafttransportsimulator/entities/instances/AEntityVehicleD_Moving.java
> +    public float currentSteeringForceIgnoration;
You're right, it should be prefixed with `current` as it's a ModifiedValue.  So `currentSteeringForceIgnoresSpeed`  it should be.

2024-03-07 19:32 UTC, DonBruce64 commented on mccore/src/main/java/minecrafttransportsimulator/entities/instances/AEntityVehicleD_Moving.java
> +    protected double getTurningForce() {
Ah, I missed that, makes sense.  What I'd do here is make the `turningForce` variable located here https://github.com/DonBruce64/MinecraftTransportSimulator/blob/a61731231e7a2ac327db4fb69bcbf631b44db042/mccore/src/main/java/minecrafttransportsimulator/entities/instances/AEntityVehicleD_Moving.java#L330C16-L330C29

a variable in the class file up top that's `protected` and reference that in your `slip_understeer`.  that way you aren't re-calculating the turning force each time you reference the variable, you're using the last-calculated value that's known correct.  Saves on processing time, and lets this method remain private as a helper method.

2024-03-07 19:34 UTC, DonBruce64 commented on mccore/src/main/java/minecrafttransportsimulator/entities/instances/EntityVehicleF_Physics.java
> +            case ("slip_understeer"):
It might be me being mistaken, but I coulda swore that's how case statements work since IF statements without curlys do the same thing.  So I keep them the same.  Either way, it's for sure fixed now!

2024-03-08 01:57 UTC, merged

2024-03-08 01:57 UTC, DonBruce64 commented
Merged.  Go forth and wiki this!