Make jetPowerFactor and bypassration VMable
DonBruce64/MinecraftTransportSimulator pull request #1787
Opened 2024-04-04 01:24 UTC by conman180

2024-04-05 20:07 UTC, boot2big commented
I don't know what this'll be usable for, but I like this.

2024-04-07 13:24 UTC, DonBruce64 requested changes

2024-04-07 13:24 UTC, DonBruce64 commented on mccore/src/main/java/minecrafttransportsimulator/entities/instances/PartEngine.java
> +    public double getJetPowerFactor() {
These aren't used anywhere?

2024-04-07 13:24 UTC, DonBruce64 commented on mccore/src/main/java/minecrafttransportsimulator/entities/instances/PartEngine.java
> +            double thrust = (vehicleOn.reverseThrust ? -(coreContribution + fanContribution) : coreContribution + fanContribution) * getJetPowerFactor();
Shouldn't you just use currentJetPowerFactor rather than a function?  You use currentBypassRatio here, use the other variable directly?

2024-04-07 17:40 UTC, conman180 commented on mccore/src/main/java/minecrafttransportsimulator/entities/instances/PartEngine.java
> +            double thrust = (vehicleOn.reverseThrust ? -(coreContribution + fanContribution) : coreContribution + fanContribution) * getJetPowerFactor();
oops oversight on my part in testing

2024-04-07 23:36 UTC, merged