Add changes to gravity
DonBruce64/MinecraftTransportSimulator pull request #1804
Opened 2024-06-08 15:23 UTC by conman180

For cars, Normalizes gravity to be 100% speed no matter the speed factor.
For anything else, allows gravity factor to be defined/modified thru VMs as motorized section definition.

Will make it so gravity factor applies on top of normalized gravity for cars upon request.

2024-07-29 14:57 UTC, DonBruce64 requested changes

2024-07-29 14:57 UTC, DonBruce64 commented on mccore/src/main/java/minecrafttransportsimulator/entities/instances/EntityVehicleF_Physics.java
> +            /*if (definition.motorized.isAircraft) {
I spy dead code...

2024-07-29 14:57 UTC, DonBruce64 commented on mccore/src/main/java/minecrafttransportsimulator/entities/instances/EntityVehicleF_Physics.java
> +            if (definition.motorized.gravityFactor != 0) {
I think you should be checking the currentGravityFactor here, not the JSON one.  If someone has 0 in the JSON, but is using VMs instead to modify it, then it won't get applied here even if it's a non-zero value.

2024-07-29 14:57 UTC, DonBruce64 commented on mccore/src/main/java/minecrafttransportsimulator/entities/instances/EntityVehicleF_Physics.java
> -            if (!definition.motorized.isAircraft) {
You removed the aircraft check in your updated code, that means that aircraft now are subject to the gravity config.  That was left out specifically because aircraft are meant to be floatier than cars.  Cars should have more gravity, but they don't because they factor the Y value by the speedFactor, which makes them go down slower.  that's ideal for planes where you need to shorten takeoff roll, but not cars where you want them to always fall down fast, just not move fast.  You'd want to check the D_Moving class where the factor is applied, and have it ignore the factor in the y-dir for cars, but not aircraft/blimps.

2024-07-29 14:58 UTC, DonBruce64 commented
Actually, does your change supercede Nax's #1792 ?

2024-08-04 06:51 UTC, conman180 commented on mccore/src/main/java/minecrafttransportsimulator/entities/instances/EntityVehicleF_Physics.java
> +            if (definition.motorized.gravityFactor != 0) {
the reason i had it like this is so that if left undefined in json, it resorts to global of 1 or whatever mts config has set. i dont think having zero gravity vehicles is a good idea

2024-08-04 06:51 UTC, conman180 commented
> Actually, does your change supercede Nax's #1792 ?

only partially. the gravity stuff yes, wheel stuff no

2024-08-04 06:54 UTC, conman180 commented on mccore/src/main/java/minecrafttransportsimulator/entities/instances/EntityVehicleF_Physics.java
> -            if (!definition.motorized.isAircraft) {
i intended to remove aircraft check in code to have it possible to modify how it acts on a plane. making it customisable vehicle to vehicle. an example use would be a totaled/shotdown plane not wanting to be floaty as it cant fly no more. so PA can make it come down quicker if they so choose.
hence why prev stated, i left it so a 0 or undefined resorts back to original behavior.

2024-08-04 23:58 UTC, conman180 commented on mccore/src/main/java/minecrafttransportsimulator/entities/instances/EntityVehicleF_Physics.java
> +            /*if (definition.motorized.isAircraft) {
yeah yeah ill get to this

2024-08-11 05:20 UTC, conman180 commented
Temporarily closing this for now to update my fork

2024-08-11 05:20 UTC, closed without merging