Adds VehicleEffects
DonBruce64/MinecraftTransportSimulator pull request #566
Opened 2020-10-20 03:41 UTC by gyrohero

2020-10-20 03:58 UTC, DonBruce64 requested changes
Couple of comments.  Also, somehow a WRL0001.tmp file found its way in here....

2020-10-20 03:58 UTC, DonBruce64 commented on src/main/java/minecrafttransportsimulator/vehicles/main/EntityVehicleB_Rideable.java
>  		if(!world.isClient()){
So, I get why you put the code to get rid of the effects here.  Only concern is that this block only executes on the server.  Will that cause syncing issues?  Effects should be either applied and removed on server/client, or only the server, but never a mix of both or de-syncs can occur.

2020-10-20 03:58 UTC, DonBruce64 commented on src/main/java/mcinterface1122/WrapperEntity.java
> +			try{
While I understand the idea of having a try/catch block here, a better way of doing this is PotionEffect = new PotionEffect(),    if(potionEffect == null) throw Exception.  Either that, or the Potion itself will be null.  Basically, something is assured to be null, so it's better to use a null check to throw than a try/catch.  Usually try/catch is for file I/O stuff like JSON parsing.

2020-10-20 15:39 UTC, gyrohero commented on src/main/java/mcinterface1122/WrapperEntity.java
> +			try{
Ok, that makes sense. Fixed.

2020-10-20 15:42 UTC, gyrohero commented on src/main/java/minecrafttransportsimulator/vehicles/main/EntityVehicleB_Rideable.java
>  		if(!world.isClient()){
Ah, that was an oversight on my part. I just put it there so it would be after the 
`VehiclePart packPart = getPackDefForLocation(riderLocation);`

That being said, would it cause any issues if I move that line out of the if-block that checks if we're on the server?

2020-10-20 16:18 UTC, gyrohero commented on src/main/java/minecrafttransportsimulator/vehicles/main/EntityVehicleB_Rideable.java
>  		if(!world.isClient()){
Assuming that doesn't cause issues, it should be fixed now.

2020-10-21 01:05 UTC, DonBruce64 commented on src/main/java/minecrafttransportsimulator/vehicles/main/EntityVehicleB_Rideable.java
>  		if(!world.isClient()){
Not an issue at all.  I just had it there because I didn't want to create the linking on the server if I didn't need it.  But now you need it, so out it goes.

2020-10-21 01:07 UTC, merged