Fixes muzzle position not mirroring with part
DonBruce64/MinecraftTransportSimulator pull request #592
Opened 2020-11-05 01:29 UTC by gyrohero

@LauraDarkez caught this bug and tested the fix for me. The fix itself worked, but she said that it also made her discover a potential problem with the mirroring system

2020-11-05 01:34 UTC, DonBruce64 commented
Going to have to decline this one.  The mirroring issue is more than just the muzzlePosition.  It also makes the gun turn the wrong way in general.  I've seen it happen frequently when you put the ragingSeagull gunner seat on cars and attach guns to them.  The proper way to fix such a thing, I think, is to flag the seat as disableMirroring : true to ensure that the rotated parts on it don't mirror themselves when they rotate.  Please let me know if that works prior to this, as I'd rather not hard-code mirrored gun logic as mirroring is designed to purely be a rendering thing only.  Though if this fix corrects both the animation and the bullet itself, that's okay.

2020-11-06 14:10 UTC, LauraDarkez commented
don i would like to point out that my lightning rocket launcher is meant to mirror on the biplane, as the firing pattern is inner to outer on both units. gyro fixed the issue of muzzlepositions not following requested mirroring. and i will disableMirroring on that gunner seat, but overall having muzzlepositions mirror when mirroring is requested, is a good thing. the issue i noticed was that muzzles were reversed in logic. so now, the muzzles do mirror properly, but the rotation-mirroring is an issue that will exist unless they are disablemirrored. that issue doesnt exist on non-rotating guns though.

2020-11-07 01:06 UTC, DonBruce64 requested changes

2020-11-07 01:06 UTC, DonBruce64 commented on src/main/java/minecrafttransportsimulator/vehicles/parts/PartGun.java
> +			Point3d firingPosition = definition.gun.muzzlePositions.get(currentMuzzle).copy();
I see you're copying the muzzlePosition here, but then making yet another new Point3d object later to return.  If you're making a copy of the object, you should be modifying the copy.  Or, if you want to make a new object, you can simply not make a copy of the muzzlePosition.  Personally, I'd keep the copy(), but change the latter to if(morringStuffs)firingPosition.x *= -1.  Basically, get a copy of the point, and if you need to mirror it, invert the x coord, and then return the copied variable.  This will be important as this logic happens every tick, and you don't want to create multiple objects if you can help it.

2020-11-07 01:07 UTC, DonBruce64 commented
That is a fair and accurate assessment for this feature.  Got just one issue with the execution, and then I can pull it in.

2020-11-11 00:29 UTC, DonBruce64 requested changes

2020-11-11 00:29 UTC, DonBruce64 commented on src/main/java/mcinterface1122/WrapperEntity.java
> +		if (entity != null && entity instanceof BuilderEntity) {
The != null check is redundant here, as instanceof takes care of that.  So you can just do:
return entity instanceof BuilderEntity ? ((BuilderEntity) entity).entity : null;

2020-11-11 00:29 UTC, DonBruce64 commented on src/main/java/minecrafttransportsimulator/rendering/instances/ParticleBullet.java
> +			MasterLoader.coreInterface.logError("Slowing down and falling");
Pretty sure you don't want this in the logs.  Pro-tip though: if you're using Eclipse or IDEA, System.out.println() works just as well, and doesn't bloat up the logs.

2020-11-11 00:29 UTC, DonBruce64 commented on src/main/java/minecrafttransportsimulator/rendering/instances/ParticleBullet.java
> +			MasterLoader.coreInterface.logError("Current velocity " + velocity + ", " + motion);
Same as other comment about this not being here.  And for the following lines too.

2020-11-11 00:29 UTC, DonBruce64 commented on src/main/java/minecrafttransportsimulator/rendering/instances/ParticleMissile.java
> +			if(entityTargetBase != null && entityTargetBase instanceof EntityVehicleF_Physics && (engineTarget == null || !engineTarget.isValid || engineTarget.temp < 30f)) {
Don't need a null check if you're using instanceof.

2020-11-11 00:29 UTC, DonBruce64 commented on src/main/java/minecrafttransportsimulator/rendering/instances/ParticleMissile.java
> +			//If there isn't a valid engine, just track the entity
Is this valid though?  Should a heat-seeking missle be tracking not-hot vehicles?  Pretty sure it shouldn't know the difference between a cold tank that isn't running and a building, so if the engine is cold because it's turned off, then it shouldn't try to track it.  Just my two pennies.

2020-11-11 00:29 UTC, DonBruce64 commented on src/main/java/minecrafttransportsimulator/packets/instances/PacketBulletHit.java
> +			if (bulletDefinition.bullet.blastStrength == 0f) bulletDefinition.bullet.blastStrength = 1f;
Is this for bomb strength?  Like TNT?  If so, I'd like to talk about this parameter, as I think this might be the wrong way to handle such a thing.

2020-11-11 02:32 UTC, gyrohero commented on src/main/java/minecrafttransportsimulator/rendering/instances/ParticleMissile.java
> +			//If there isn't a valid engine, just track the entity
Fair enough

2020-11-11 04:04 UTC, merged